version: '3'
services:
  frontend:
    build:
      context: ../../Frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - frontend-volume:/app/frontend
    networks:
      - my-network
  backend:
    build:
      context: ../../Backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database
    volumes:
      - backend-volume:/app/backend
    networks:
      - my-network
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - database-volume:/var/lib/postgresql/data
networks:
  my-network:
volumes:
  frontend-volume:
  backend-volume:
  database-volume:
